{
  "throws": "Unexpected await for `for-in`"
}